Workshop Class
WhitmanCSCapstone/ge-scheduling pull request #22
Opened 2019-10-31 19:58 UTC by Chris-Pyles

adds workshop class used to describe each workshop and all its properties including
+ name
+ number
+ capacity (total and per session)
+ popularity score
+ variables to check if a session is full or "full enough"
+ function to update all aforementioned variables
+ function to add student to a given session
+ function to set a session's capacity manually

2019-11-03 22:09 UTC, Izayuh approved these changes

2019-11-03 22:53 UTC, beszel requested changes

2019-11-03 22:53 UTC, beszel commented on main.js
> +    }
Is it appropriate to refactor this into a method? I think it would help simplify the constructor.

2019-11-03 22:53 UTC, beszel commented on main.js
> +    this.statusUpdate = function() {
The boolean properties could be replaced with methods that perform these calculations when called.

2019-11-04 02:58 UTC, tvu212 approved these changes

2019-11-06 02:38 UTC, beszel approved these changes
Yes, good and cool

2019-11-06 02:39 UTC, merged