Getdata
WhitmanCSCapstone/ge-scheduling pull request #38
Opened 2019-12-08 22:47 UTC by tvu212

All of the input data as well as the output data besides the spreadsheet now reads from the active sheet.

2019-12-10 18:26 UTC, Chris-Pyles commented on main.js
> +        .createMenu("Great Explorations")spreadsheet
"spreadsheet" doesn't look like it should be here

2019-12-10 18:28 UTC, Chris-Pyles commented on main.js
> +var responseSheet = spreadsheet.getSheets()[0];
all instances of "spreadsheet.getSheets()[x] return undefined

2019-12-10 18:33 UTC, Chris-Pyles commented on main.js
> +outputSheet.clear();
output sheet cannot be cleared since it's still undefined

2019-12-10 18:34 UTC, Chris-Pyles submitted a review, later dismissed
Some of the sheet-reading doesn't seem to read the correct data. The only sheet currently defined correctly is the workshop sheet.

2019-12-11 04:54 UTC, tvu212 commented
It might not have been working since your personal test environment did not have have the other two sheets available which is why they were null or undeclared. I rewrote the code so now we are all pulling input and output to the same spreadsheet no matter what test environment we are in. So instead of using activesheet I call the ID number of the document.

2020-01-02 03:43 UTC, irhawk commented
@tvu212 Can you document steps for testing these changes?

2020-01-04 07:48 UTC, beszel requested changes

2020-01-04 07:48 UTC, beszel commented on main.js
> +var responseSheet = RESPONSE_SPREADSHEET.getSheets()[0];
Can you replace these numbers with variables? You could use an object to replace `[0]` with `[SHEET_INDICES.responses]`:
```
SHEET_INDICES = {
    responses: 0,
    output: 1
}
```

2020-01-04 07:48 UTC, beszel commented on main.js
> +var RESPONSE_SHEET_ID = "1YcO_lYO1hp9j3fBxWm-4AF_AfYCPExeuVyaJzw0Yktk";
Can we change this variable name to reflect that the response data is only one sheet in this larger spreadsheet? We can use "SPREADSHEET" for both of these while we're at it to clarify that it's a spreadsheet ID.

2020-01-04 07:48 UTC, beszel commented on main.js
> +var workshopSheet = SpreadsheetApp.openById(WORKSHOP_SHEET_ID);
Do these need to be defined globally, outside of a function? Can they be moved into a function and passed in as arguments where needed? If they need to be global, we can make them all capitals.

2020-01-04 07:50 UTC, irhawk commented
Removed @Izayuh from reviewers because Chris and I are reviewing this one.

2020-01-12 05:21 UTC, irhawk commented
@tvu212 Can you address more of my requested changes?

2020-01-13 07:19 UTC, tvu212 commented
Yeah sounds good I'll get these done by tomorrow!

2020-01-14 16:58 UTC, Chris-Pyles approved these changes

2020-01-19 18:53 UTC, tvu212 commented on main.js
> +var workshopSheet = SpreadsheetApp.openById(WORKSHOP_SHEET_ID);
Yes these should be global unless you want the function to be declared every time the workShop sheet is referenced. I'll change to make them all capitals

2020-01-19 19:06 UTC, tvu212 commented on main.js
> +var responseSheet = RESPONSE_SPREADSHEET.getSheets()[0];
Done

2020-01-19 19:14 UTC, tvu212 commented on main.js
> +var RESPONSE_SHEET_ID = "1YcO_lYO1hp9j3fBxWm-4AF_AfYCPExeuVyaJzw0Yktk";
Can you elaborate. I've made the changes I think you've wanted.

2020-01-19 23:07 UTC, beszel reviewed
This looks good, how can I test it?

2020-01-19 23:07 UTC, irhawk commented on main.js
> +//VARIABLES FOR RESPONSE SPREADSHEET INDICES
Why is this comment changed to capitals?

2020-01-20 07:39 UTC, irhawk commented on main.js
> +var RESPONSE_SHEET_ID = "1YcO_lYO1hp9j3fBxWm-4AF_AfYCPExeuVyaJzw0Yktk";
Looks good, that's all I had in mind.

2020-01-22 00:24 UTC, merged