Matcher function testing
WhitmanCSCapstone/ge-scheduling pull request #56
Opened 2020-02-20 08:34 UTC by Chris-Pyles

**What did you do to resolve the issue? Explain your changes.**
This is a fully working version of the matching algorithm that produces viable matches for each student while filling each workshop to a set minimum capacity.

**Describe the steps to test your changes.**

-   Run main() from your dev file to run the matcher algorithm.
-   An error may appear due to randomness if a student cannot be given one of their preferred workshops during final matching.
-   Changing Matcher.minimumWorkshopFill to a value above 0.70 may result in an error where a workshop could not be sufficiently filled.
-   Changing Matcher.minimumWorkshopFill to a value too low (IE, 0.3) will result in an error where a student could not be given one of their preferred workshops during final matching.
-   The output sheet should display a complete set of matches for every student in the document, including each workshop's number, name, and location.

2020-02-21 00:54 UTC, Izayuh commented on Workshop.js
>      this.toString = function() {
I don't think we're using this function anymore.

2020-02-21 01:18 UTC, Izayuh commented on Matcher.js
>          this.workshopsByPopularity = [];
I would assume this variable name would sort from highest popularity to lowest, would it be better practice to rename this something like "workshopsByUnpopularity" or "workshopsByLowPopularity"?

2020-02-21 01:24 UTC, Izayuh commented on Matcher.js
> +        this.fullEnough = [];
We've mostly been using "Quorum" in the code to refer to workshops being "full enough", we may want to remain consistent with these variable names.

2020-02-23 21:50 UTC, Izayuh approved these changes

2020-02-23 22:56 UTC, beszel requested changes

2020-02-23 22:56 UTC, irhawk commented on Student.js
> +            Logger.log(workshop.name);
Are these log messages still relevant? If they are, could you prepend each of them with a descriptive string to make the logs clearer?

2020-02-23 23:09 UTC, merged