Scorer
WhitmanCSCapstone/ge-scheduling pull request #9
Opened 2019-10-06 19:46 UTC by Izayuh

Simple prototype for our scoring function.

2019-10-06 20:01 UTC, tvu212 approved these changes

2019-10-09 00:29 UTC, Chris-Pyles approved these changes

2019-10-09 00:42 UTC, tvu212 approved these changes

2019-10-09 00:54 UTC, beszel requested changes

2019-10-09 00:54 UTC, irhawk commented on main.gs
> +            score += 12;
Write constants to remove these magic numbers. Can you refactor this block to reduce repetition? What about a helper function?

2019-10-09 00:54 UTC, irhawk commented on main.gs
> +
Add doctag

2019-10-20 20:07 UTC, irhawk commented
If a student doesn't get any of their preferences, they get a perfect score of 0. They should get a worse score than that.

2019-10-27 20:30 UTC, Chris-Pyles approved these changes

2019-10-29 00:06 UTC, Chris-Pyles approved these changes

2019-10-29 00:24 UTC, Chris-Pyles commented
this SHOULD be set for approval now, but it says there are conflicts. I feel like this has to do with the fact that master branch has main.js and scorer has main.gs. We might want to make them the same filetype for the future.

2019-10-29 00:48 UTC, merged